default:
  tags: [saas-linux-large-amd64]

include:
  - template: gitlab-ci.yml

test:
  allow_failure: true

build:
  stage: build
  image: maven:3-jdk-8-slim
  variables:
    CI_DEBUG_TRACE: "false"
    JOB_TRACE: "false"
    SECURE_LOG_LEVEL: "false"
    TRACE: "false"
    AUTO_DEVOPS_DEPLOY_DEBUG: "false"
  script:
    - mvn clean install -DskipTests=false
    - mvn package -DskipTests=false -Dmaven.repo.local=./.m2
  cache:
    policy: push
    key: ${CI_COMMIT_SHA}
    paths:
      - .m2
  artifacts:
    paths:
    - "Dockerfile"
    - "target/spring-petclinic-1.5.4.jar"

push:
  services:
  - name: docker:20.10.6-dind
  image: docker:20.10.6
  variables:
    DOCKER_DRIVER: overlay2
  stage: build
  needs: [build]
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --tag $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:latest .
    - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:latest



